# 1. [Say "Hello, World!" With Python](https://www.hackerrank.com/challenges/py-hello-world/problem?isFullScreen=true)

Here is a sample line of code that can be executed in Python:<br>
    <p>&emsp;print("Hello, World!")</p>

You can just as easily store a string as a variable and then print it to stdout:<br>
 <p>&emsp;my_string = "Hello, World!"<br>
    &emsp;print(my_string) </p>

The above code will print Hello, World! on your screen. Try it yourself in the editor below!

**Input Format**

You do not need to read any input in this challenge.

**Output Format**

Print Hello, World! to stdout.

**Sample Output 0**

Hello, World!

In [1]:
print("Hello, World!")

Hello, World!


# 2. [Python If-Else](https://www.hackerrank.com/challenges/py-if-else/problem?isFullScreen=true)

**Task**<br>
Given an integer, *n*, perform the following conditional actions:
* If *n* is odd, print Weird
* If *n* is even and in the inclusive range of **2** to **5**, print Not Weird
* If *n* is even and in the inclusive range of **6** to **20**, print Weird
* If *n* is even and greater than **20**, print Not Weird

**Input Format**

A single line containing a positive integer, .

**Constraints**
* **1 <= n <= 100**

**Output Format**

Print Weird if the number is weird. Otherwise, print Not Weird.

**Sample Input 0**<br>
3

**Sample Output 0**<br>
Weird

**Explanation 0**<br>
*n* = **3**

*n* is odd and odd numbers are weird, so print Weird.

**Sample Input 1**<br>
24

**Sample Output 1**<br>
Not Weird

**Explanation 1**<br>
*n* = **24**

*n* > **20** and *n* is even, so it is not weird.

In [2]:
n = int(input().strip())
if n%2==0 and n>20:
    print("Not Weird")
elif n%2==0 and (n>=6 and n<=20):
    print("Weird")
elif n%2==0 and (n>=2 and n<=5):
    print("Not Weird")
else:
    print("Weird")

24
Not Weird


# 3. [Arithmetic Operators](https://www.hackerrank.com/challenges/python-arithmetic-operators/problem?isFullScreen=true)

**Task**<br>
The provided code stub reads two integers from STDIN,  and . Add code to print three lines where:
1. The first line contains the sum of the two numbers.
2. The second line contains the difference of the two numbers (first - second).
3. The third line contains the product of the two numbers.

**Example**<br>
*a* = 3<br>
*b* = 5<br>

Print the following:<br>
8<br>
-2<br>
15<br>

**Input Format**<br>
The first line contains the first integer, *a*.<br>
The second line contains the second integer, *b*.

**Constraints**
* 1 <= a <= 10<sup>10</sup>
* 1 <= b <= 10<sup>10</sup>

**Output Format**<br>
Print the three lines as explained above.

**Sample Input 0**<br>
3<br>
2

**Sample Output 0**<br>
5<br>
1<br>
6

**Explanation 0**<br>
**3+2 => 5**<br>
**3-2 => 1**<br>
**3*2 => 6**<br>

In [3]:
a = int(input())
b = int(input())
print(a+b)
print(a-b)
print(a*b)

3
2
5
1
6


# 4. [Python: Division](https://www.hackerrank.com/challenges/python-division/problem?isFullScreen=true)

**Task**<br>
The provided code stub reads two integers, *a* and *b*, from STDIN.

Add logic to print two lines. The first line should contain the result of integer division, *a* // *b*. The second line should contain the result of float division, *a* / *b*.

No rounding or formatting is necessary.

**Example**<br>
**a = 3**<br>
**b = 5**

* The result of the integer division **3//5=0**.
* The result of the float division is **3/5=0.6**.

Print:<br>
0<br>
0.6

**Input Format**<br>
The first line contains the first integer, **a**.<br>
The second line contains the second integer, **b**.

**Output Format**<br>
Print the two lines as described above.

**Sample Input 0**<br>
4<br>
3

**Sample Output 0**<br>
1<br>
1.33333333333

In [4]:
a = int(input())
b = int(input())
print(a//b)
print(a/b)

4
3
1
1.3333333333333333


# 5. [Loops](https://www.hackerrank.com/challenges/python-loops/problem?isFullScreen=true)

**Task**<br>

The provided code stub reads and integer, **n**, from STDIN. For all non-negative integers **i < n, print i<sup>2</sup>**.

**Example**<br>
*n = 3*

The list of non-negative integers that are less than *n = 3* is [0, 1, 2]. Print the square of each number on a separate line.

0<br>
1<br>
4

**Input Format**<br>
The first and only line contains the integer, *n*.

**Constraints**<br>
*1 <= n <= 20*

**Output Format**<br>
Print *n* lines, one corresponding to each *i*.

**Sample Input 0**<br>
5

**Sample Output 0**
0<br>
1<br>
4<br>
9<br>
16

In [6]:
n = int(input())
i = 0
while n>0:
    print(i*i)
    i = i+1
    n = n-1

5
0
1
4
9
16


# 6. [Print Function](https://www.hackerrank.com/challenges/python-print/problem?isFullScreen=true)

The included code stub will read an integer, *n*, from STDIN.

Without using any string methods, try to print the following:<br>
**123...n**

Note that **"..."** represents the consecutive values in between.

**Example**<br>
**n = 5**<br>
Print the string **12345**.

**Input Format**<br>
The first line contains an integer **n**.

**Constraints**<br>
**1 <= n <= 150**

**Output Format**<br>
Print the list of integers from **1** through **n** as a string, without spaces.

**Sample Input 0**<br>
**3**

**Sample Output 0**<br>
**123**

In [7]:
n = int(input())
i = 1
while n>0:
    print(str(i),end="")
    i = i+1
    n = n-1

5
12345

# 7. [List Comprehensions](https://www.hackerrank.com/challenges/list-comprehensions/problem?isFullScreen=true)

Let's learn about list comprehensions! You are given three integers *x, y* and *z* representing the dimensions of a cuboid along with an integer *n*. Print a list of all possible coordinates given by *(i, j, k)* on a 3D grid where the sum of *i + j + k* is not equal to *n*. Here, **0 <= i <= x; 0 <= j <= y; 0 <= k <= z**. Please use list comprehensions rather than multiple loops, as a learning exercise.

**Example**<br>
*x = 1*<br>
*y = 1*<br>
*z = 2*<br>
*n = 3*

All permutations of *[i, j, k]* are:<br>
[[0,0,0],[0,0,1],[0,0,2],[0,1,0],[0,1,1],[0,1,2],[1,0,0],[1,0,1],[1,0,2],[1,1,0],[1,1,1],[1,1,2]]

Print an array of the elements that do not sum to *n=3*.<br>
[[0,0,0],[0,0,1],[0,0,2],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,2]]

**Input Format**<br>
Four integers *x,y,z* and *n*, each on a separate line.

**Constraints**<br>
Print the list in lexicographic increasing order.

**Sample Input 0**<br>
1<br>
1<br>
1<br>
2

**Sample Output 0**<br>
[[0,0,0],[0,0,1],[0,1,0],[1,0,0],[1,1,1]]

**Explanation 0**<br>
Each variable  and  will have values of **0** or **1**. All permutations of lists in the form<br>
[i,j,k] = [[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]].<br>
Remove all arrays that sum to **n=2** to leave only the valid permutations.

**Sample Input 1**<br>
2<br>
2<br>
2<br>
2

**Sample Output 1**<br>
[[0,0,0],[0,0,1],[0,1,0],[0,1,2],[0,2,1],[0,2,2],[1,0,0],[1,0,2],[1,1,1],[1,1,2],[1,2,0],[1,2,1],[1,2,2],[2,0,1],[2,0,2],[2,1,0],[2,1,1],[2,1,2],[2,2,0],[2,2,1],[2,2,2]]

In [8]:
x = int(input())
y = int(input())
z = int(input())
n = int(input())
print(list([i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1) if i+j+k !=n))

1
1
1
2
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


# 8. [Find the Runner-Up Score!](https://www.hackerrank.com/challenges/find-second-maximum-number-in-a-list/problem?isFullScreen=true)

Given the participants' score sheet for your University Sports Day, you are required to find the runner-up score. You are given *n* scores. Store them in a list and find the score of the runner-up.

**Input Format**<br>
The first line contains *n*. The second line contains an array *A*[ ] of *n* integers each separated by a space.

**Constraints**<br>
* **2 <= n <= 10**
* **-100 <= A[i] <= 100**

**Output Format**<br>
Print the runner-up score.

**Sample Input 0**<br>
5<br>
2 3 6 6 5

**Sample Output 0**<br>
5<br>

**Explanation 0**<br>
Given list is **[2,3,6,6,5]**. The maximum score is **6**, second maximum is **5**. Hence, we print **5** as the runner-up score.

In [9]:
n = int(input())
arr = map(int, input().split())
arr = list(arr)
x = max(arr)
y = -100
for i in range(0,n):
    if arr[i]<x and arr[i] > y:
        y = arr[i]

print(y)

5
2 3 6 6 5
5


# 9. [Finding the percentage](https://www.hackerrank.com/challenges/finding-the-percentage/problem?isFullScreen=true)

The provided code stub will read in a dictionary containing key/value pairs of name:[marks] for a list of students. Print the average of the marks array for the student name provided, showing 2 places after the decimal.

**Example**<br>
marks key:value pairs are<br>
'alpha': [20,30,40]<br>
'beta': [30,50,70]<br>
query_name = 'beta'

The **query_name is** 'beta'. beta's average score is **(30 + 50 + 70)/3 = 50.0**.

**Input Format**<br>
The first line contains the integer **n**, the number of students' records. The next **n** lines contain the names and marks obtained by a student, each value separated by a space. The final line contains **query_name**, the name of a student to query.

**Constraints**<br>
* **2 <= n <= 10**
* **0 <= marks[i] <= 100**
* length of marks arrays = 3

**Output Format**<br>
Print one line: The average of the marks obtained by the particular student correct to 2 decimal places.

**Sample Input 0**<br>
3<br>
Krishna 67 68 69<br>
Arjun 70 98 63<br>
Malika 52 56 60<br>
Malika

**Sample Output 0**<br>
56.00

**Explanation 0**<br>
Marks for Malika are **{52,56,60}** whose average is **(52+56+60)/3 => 56**

**Sample Input 1**<br>
2<br>
Harsh 25 26.5 28<br>
Anurag 26 28 30<br>
Harsh

**Sample Output 1**<br>
26.50

In [10]:
n = int(input())
student_marks = {}
for _ in range(n):
    name, *line = input().split()
    scores = list(map(float, line))
    student_marks[name] = scores
query_name = input()
x = 0
for i in student_marks[query_name]:
    x = x+i
ans = x/3
print("{:.2f}".format(ans))

2
Harsh 25 26.5 28
Anurag 26 28 30
Harsh
26.50


# 10. [What's Your Name?](https://www.hackerrank.com/challenges/whats-your-name/problem?isFullScreen=true)

You are given the firstname and lastname of a person on two different lines. Your task is to read them and print the following:

Hello firstname lastname! You just delved into python.

**Function Description**<br>
Complete the print_full_name function in the editor below.<br>
print_full_name has the following parameters:
* string first: the first name
* string last: the last name

**Prints**<br>
* string: 'Hello **firstname lastname**! You just delved into python' where **firstname** and **lastname** are replaced with **first** and **last**.

**Input Format**<br>
The first line contains the first name, and the second line contains the last name.

**Constraints**<br>
The length of the first and last names are each ≤ **10**.

**Sample Input 0**<br>
Ross<br>
Taylor<br>

**Sample Output 0**<br>
Hello Ross Taylor! You just delved into python.

**Explanation 0**<br>
The input read by the program is stored as a string data type. A string is a collection of characters.

In [11]:
def print_full_name(first, last):
    print("Hello {x} {y}! You just delved into python.".format(x=first,y=last))

first_name = input()
last_name = input()
print_full_name(first_name, last_name)

Ross
Taylor
Hello Ross Taylor! You just delved into python.


# 11. [Nested Lists](https://www.hackerrank.com/challenges/nested-list/problem?isFullScreen=true)

Given the names and grades for each student in a class of **N** students, store them in a nested list and print the name(s) of any student(s) having the second lowest grade.

**Note:** If there are multiple students with the second lowest grade, order their names alphabetically and print each name on a new line.

**Example**<br>
**records = [["chi",20.0],["beta",50.0],["alpha",50.0]]**<br>
The ordered list of scores is **[20.0,50.0]**, so the second lowest score is **50.0**. There are two students with that score: **["beta","alpha"]**. Ordered alphabetically, the names are printed as:

`alpha`<br>
`beta`

**Input Format**

The first line contains an integer, **N**, the number of students.
The **2N** subsequent lines describe each student over **2** lines.
- The first line contains a student's name.
- The second line contains their grade.

**Constraints**<br>
* **2 <= N <= 5**
* There will always be one or more students having the second lowest grade.

**Output Format**

Print the name(s) of any student(s) having the second lowest grade in. If there are multiple students, order their names alphabetically and print each one on a new line.

**Sample Input 0**<br>
5<br>
Harry<br>
37.21<br>
Berry<br>
37.21<br>
Tina<br>
37.2<br>
Akriti<br>
41<br>
Harsh<br>
39

**Sample Output 0**<br>
Berry<br>
Harry

**Explanation 0**

There are **5** students in this class whose names and grades are assembled to build the following list:

`python students = [['Harry', 37.21], ['Berry', 37.21], ['Tina', 37.2], ['Akriti', 41], ['Harsh', 39]]`

The lowest grade of **37.2** belongs to Tina. The second lowest grade of **37.21** belongs to both Harry and Berry, so we order their names alphabetically and print each name on a new line.

In [1]:
records = []
scores = []
for _ in range(int(input())):
    name = input()
    score = float(input())
    records.append([name, score])
    scores.append(score)

sec_score = sorted(set(scores))[1]
lst = []
for i in range(len(records)):
    if sec_score == records[i][1]:
        lst.append(records[i])
lst = sorted(lst)
for i in range(len(lst)):
    print(lst[i][0])

5
Harry
37.21
Berry
37.21
Tina
37.2
Akriti
41
Harsh
39
Berry
Harry


# 12. [Lists](https://www.hackerrank.com/challenges/python-lists/problem?isFullScreen=true)

Consider a list (list = []). You can perform the following commands:
1. `insert i e`: Insert integer  at position .
2. `print`: Print the list.
3. `remove e`: Delete the first occurrence of integer .
4. `append e`: Insert integer  at the end of the list.
5. `sort`: Sort the list.
6. `pop`: Pop the last element from the list.
7. `reverse`: Reverse the list.

Initialize your list and read in the value of **n** followed by **n** lines of commands where each command will be of the **7** types listed above. Iterate through each command in order and perform the corresponding operation on your list.

**Example**<br>
**N = 4
append 1
append 2
insert 3 1
print**

* **append 1**: Append **1** to the list, **arr = [1]**.
* **append 2**: Append **2** to the list, **arr = [1,2]**.
* **insert 3 1**: Insert **3** at index **1**, **arr = [1,3,2]**.
* **print**: Print the array.

**Output:**<br>
`[1, 3, 2]`

**Input Format**

The first line contains an integer, **n**, denoting the number of commands.
Each line **i** of the **n** subsequent lines contains one of the commands described above.

**Constraints**
* The elements added to the list must be integers.

**Output Format**

For each command of type print, print the list on a new line.

**Sample Input 0**<br>
12<br>
insert 0 5<br>
insert 1 10<br>
insert 0 6<br>
print<br>
remove 6<br>
append 9<br>
append 1<br>
sort<br>
print<br>
pop<br>
reverse<br>
print<br>

**Sample Output 0**<br>
[6, 5, 10]<br>
[1, 5, 9, 10]<br>
[9, 5, 1]<br>

In [2]:
N = int(input())
lst = []
for i in range(N):
    comand = input().split()

    if comand[0] == 'insert':
        lst.insert(int(comand[1]), int(comand[2]))
    if comand[0] == 'print':
        print(lst)
    if comand[0] == 'remove':
        lst.remove(int(comand[1]))
    if comand[0] == 'append':
        lst.append(int(comand[1]))
    if comand[0] == 'sort':
        lst.sort()
    if comand[0] == 'pop':
        lst.pop()
    if comand[0] == 'reverse':
        lst.reverse()

12
insert 0 5
insert 1 10
insert 0 6
print
[6, 5, 10]
remove 6
append 9
append 1
sort
print
[1, 5, 9, 10]
pop
reverse
print
[9, 5, 1]


# 13. [Tuples](https://www.hackerrank.com/challenges/python-tuples/problem?isFullScreen=true)

**Task**
Given an integer, **n**, and **n** space-separated integers as input, create a tuple, **t**, of those **n** integers. Then compute and print the result of **hash(t)**.

**Note:** [hash()](https://docs.python.org/3/library/functions.html#hash) is one of the functions in the `__builtins__` module, so it need not be imported.

**Input Format**

The first line contains an integer, **n**, denoting the number of elements in the tuple.
The second line contains **n** space-separated integers describing the elements in tuple **t**.

**Output Format**

Print the result of **hash(t)**.

**Sample Input 0**<br>
2<br>
1 2

**Sample Output 0**

3713081631934410656

In [4]:
# It only run in Pypy3
n = int(input())
int_lst = tuple(map(int, input().split()))
print(int_lst)
x = hash(int_lst)
print(x)

# 14. [sWAP cASE](https://www.hackerrank.com/challenges/swap-case/problem?isFullScreen=true)

You are given a string and your task is to swap cases. In other words, convert all lowercase letters to uppercase letters and vice versa.

**For Example:**<br>
`Www.HackerRank.com → wWW.hACKERrANK.COM`<br>
`Pythonist 2 → pYTHONIST 2`

**Function Description**

Complete the swap_case function in the editor below.<br>
swap_case has the following parameters:<br>
* string s: the string to modify

**Returns**

* string: the modified string

**Input Format**

A single line containing a string **s**.

**Constraints**<br>
**0 < len(s) <= 1000**

**Sample Input 0**<br>
HackerRank.com presents "Pythonist 2".

**Sample Output 0**<br>
hACKERrANK.COM PRESENTS "pYTHONIST 2".

In [5]:
def swap_case(s):
    s = list(s)
    for i in range(len(s)):
        if s[i].isupper():
            s[i] = s[i].lower()
        elif s[i].islower():
            s[i] = s[i].upper()
    s = ''.join(s)
    return s

s = input()
result = swap_case(s)
print(result)

HackerRank.com presents "Pythonist 2".
hACKERrANK.COM PRESENTS "pYTHONIST 2".


# 15. [String Split and Join](https://www.hackerrank.com/challenges/python-string-split-and-join/problem?isFullScreen=true)

In Python, a string can be split on a delimiter.

**Example:**

`>>> a = "this is a string"`<br>
`>>> a = a.split(" ") # a is converted to a list of strings.`<br>
`>>> print a`<br>
`['this', 'is', 'a', 'string']`

Joining a string is simple:

`>>> a = "-".join(a)`<br>
`>>> print a`<br>
`this-is-a-string`

**Task**<br>
You are given a string. Split the string on a " " (space) delimiter and join using a - hyphen.

**Function Description**

Complete the split_and_join function in the editor below.

split_and_join has the following parameters:
* string line: a string of space-separated words

**Returns**
* string: the resulting string

**Input Format**<br>
The one line contains a string consisting of space separated words.

**Sample Input**<br>
`this is a string`

**Sample Output**<br>
`this-is-a-string`

In [6]:
def split_and_join(line):
    line = line.split()
    line = "-".join(line)
    return line

line = input()
result = split_and_join(line)
print(result)

this is a string
this-is-a-string


# 16. [Mutations](https://www.hackerrank.com/challenges/python-mutations/problem?isFullScreen=true)

We have seen that lists are mutable (they can be changed), and tuples are immutable (they cannot be changed).

Let's try to understand this with an example.

You are given an immutable string, and you want to make changes to it.

**Example**<br>
`>>> string = "abracadabra"`

You can access an index by:<br>
`>>> print string[5]`<br>
`a`

What if you would like to assign a value?<br>
`>>> string[5] = 'k'`<br>
`Traceback (most recent call last):`<br>
`  File "<stdin>", line 1, in <module>`<br>
`TypeError: 'str' object does not support item assignment`<br>

How would you approach this?
* One solution is to convert the string to a list and then change the value.

**Example**<br>
`>>> string = "abracadabra"`<br>
`>>> l = list(string)`<br>
`>>> l[5] = 'k'`<br>
`>>> string = ''.join(l)`<br>
`>>> print string`<br>
`abrackdabra`
* Another approach is to slice the string and join it back.

**Example**<br>
`>>> string = string[:5] + "k" + string[6:]`<br>
`>>> print string`<br>
`abrackdabra`

**Task**<br>
Read a given string, change the character at a given index and then print the modified string.

**Function Description**<br>
Complete the mutate_string function in the editor below.<br>
mutate_string has the following parameters:
* string string: the string to change
* int position: the index to insert the character at
* string character: the character to insert

**Returns**<br>
* string: the altered string

**Input Format**<br>
The first line contains a string, **string**.<br>
The next line contains an integer **position**, the index location and a string **character**, separated by a space.

**Sample Input**

    STDIN           Function
    ------          ---------
    abracadabra     s = 'abracadabra'
    5 k             position = 5, character = 'k'

**Sample Output**<br>
`abrackdabra`

In [7]:
def mutate_string(string, position, character):
    string = list(string)
    string[position] = character
    string = ''.join(string)
    return string

s = input()
i, c = input().split()
s_new = mutate_string(s, int(i), c)
print(s_new)

abracadabra
5 k
abrackdabra


# 17. [String Validators](https://www.hackerrank.com/challenges/string-validators/problem?isFullScreen=true)

Python has built-in string validation methods for basic data. It can check if a string is composed of alphabetical characters, alphanumeric characters, digits, etc.

[str.isalnum()](https://docs.python.org/2/library/stdtypes.html#str.isalnum)<br>
This method checks if all the characters of a string are alphanumeric (a-z, A-Z and 0-9).

`>>> print 'ab123'.isalnum()`<br>
`True`<br>
`>>> print 'ab123#'.isalnum()`<br>
`False`

[str.isalpha()](https://docs.python.org/2/library/stdtypes.html#str.isalpha)<br>
This method checks if all the characters of a string are alphabetical (a-z and A-Z).

`>>> print 'abcD'.isalpha()`<br>
`True`<br>
`>>> print 'abcd1'.isalpha()`<br>
`False`

[str.isdigit()](https://docs.python.org/2/library/stdtypes.html#str.isdigit)<br>
This method checks if all the characters of a string are digits (0-9).

`>>> print '1234'.isdigit()`<br>
`True`<br>
`>>> print '123edsd'.isdigit()`<br>
`False`<br>

[str.islower()](https://docs.python.org/2/library/stdtypes.html#str.islower)<br>
This method checks if all the characters of a string are lowercase characters (a-z).

`>>> print 'abcd123#'.islower()`<br>
`True`<br>
`>>> print 'Abcd123#'.islower()`<br>
`False`

[str.isupper()](https://docs.python.org/2/library/stdtypes.html#str.isupper)<br>
This method checks if all the characters of a string are uppercase characters (A-Z).

`>>> print 'ABCD123#'.isupper()`<br>
`True`<br>
`>>> print 'Abcd123#'.isupper()`<br>
`False`<br>

**Task**<br>
You are given a string **S**.<br>
Your task is to find out if the string **S** contains: alphanumeric characters, alphabetical characters, digits, lowercase and uppercase characters.

**Input Format**<br>
A single line containing a string **S**.

**Constraints**<br>
**0 < len(S) < 1000**

**Output Format**<br>
In the first line, print True if **S** has any alphanumeric characters. Otherwise, print `False`.<br>
In the second line, print True if **S** has any alphabetical characters. Otherwise, print `False`.<br>
In the third line, print True if **S** has any digits. Otherwise, print `False`.<br>
In the fourth line, print True if **S** has any lowercase characters. Otherwise, print `False`.<br>
In the fifth line, print True if **S** has any uppercase characters. Otherwise, print `False`.

**Sample Input**<br>
`qA2`

**Sample Output**<br>
`True`<br>
`True`<br>
`True`<br>
`True`<br>
`True`

In [8]:
s = input()
print(any([i.isalnum() for i in s]))
print(any([i.isalpha() for i in s]))
print(any([i.isdigit() for i in s]))
print(any([i.islower() for i in s]))
print(any([i.isupper() for i in s]))

qA2
True
True
True
True
True


# 18. [Capitalize!](https://www.hackerrank.com/challenges/capitalize/problem?isFullScreen=true)

You are asked to ensure that the first and last names of people begin with a capital letter in their passports. For example, `alison heck` should be capitalised correctly as `Alison Heck`.

<font color="red">a</font>lison <font color="red">h</font>eck => Alison Heck

Given a full name, your task is to capitalize the name appropriately.

**Input Format**<br>
A single line of input containing the full name, **S**.

**Constraints**
* **0 < len(S) < 1000**
* The string consists of alphanumeric characters and spaces.

**Note:** in a word only the first character is capitalized. Example 12abc when capitalized remains 12abc.

**Output Format**<br>
Print the capitalized string, **S**.

**Sample Input**<br>
`chris alan`

**Sample Output**<br>
`Chris Alan`

In [9]:
def solve(s):
    s = s.split(" ")
    for i in range(0,len(s)):
        s[i] = s[i].capitalize()

    p = " ".join(s)
    return p

fptr = open(os.environ['OUTPUT_PATH'], 'w')
s = input()
result = solve(s)
fptr.write(result + '\n')
fptr.close()

chris alan


'Chris Alan'

# 19. [Polar Coordinates](https://www.hackerrank.com/challenges/polar-coordinates/problem?isFullScreen=true)

[Polar coordinates](https://en.wikipedia.org/wiki/Polar_coordinate_system) are an alternative way of representing Cartesian coordinates or [Complex Numbers](https://en.wikipedia.org/wiki/Complex_number).

A complex number **z**
> **z = x + yj**<br>

is completely determined by its real part **x** and imaginary part **y**.<br>
Here, **j** is the [imaginary unit](https://en.wikipedia.org/wiki/Imaginary_unit).
<img src='https://s3.amazonaws.com/hr-challenge-images/9951/1440141121-5b051fd241-Capture.PNG'>
A polar coordinate (**r**,**Ø**)

is completely determined by modulus **r** and phase angle **Ø**.

If we convert complex number  to its polar coordinate, we find:<br>
**r**: Distance from **z** to origin, i.e., **√(x<sup>2</sup>+y<sup>2</sup>)**<br>
**Ø**: Counter clockwise angle measured from the positive **x**-axis to the line segment that joins **z** to the origin.

Python's [cmath](https://docs.python.org/2/library/cmath.html) module provides access to the mathematical functions for complex numbers.

**cmath.phase**<br>
This tool returns the phase of complex number **z** (also known as the argument of **z**).

> `>>> phase(complex(-1.0, 0.0))`<br>
> `3.1415926535897931`

**abs**<br>
This tool returns the modulus (absolute value) of complex number **z**.

> `>>> abs(complex(-1.0, 0.0))`<br>
> `1.0`

**Task**<br>
You are given a complex **z**. Your task is to convert it to polar coordinates.

**Input Format**<br>
A single line containing the complex number **z**. Note: complex() function can be used in python to convert the input as a complex number.

**Constraints**<br>
Given number is a valid complex number

**Output Format**<br>
Output two lines:<br>
The first line should contain the value of **r**.<br>
The second line should contain the value of **Ø**.

**Sample Input**
> 1+2j

**Sample Output**
> `2.23606797749979`<br>
> `1.1071487177940904`

`Note: The output should be correct up to 3 decimal places.`

In [10]:
import cmath as c

a = complex(input())
print(abs(a))
print(c.phase(a))

1+2j
2.23606797749979
1.1071487177940904


# 20. [Power - Mod Power](https://www.hackerrank.com/challenges/python-power-mod-power/problem?isFullScreen=true)

So far, we have only heard of Python's powers. Now, we will witness them!

Powers or exponents in Python can be calculated using the built-in power function. Call the power function **a<sup>b</sup>** as shown below:

`>>> pow(a,b)`<br>
or<br>
`>>> a**b`

It's also possible to calculate **a<sup>b</sup> mod m**.

`>>> pow(a,b,m)`

This is very helpful in computations where you have to print the resultant % mod.

**Note:** Here, **a** and **b** can be floats or negatives, but, if a third argument is present, **b** cannot be negative.

**Note:** Python has a math module that has its own pow(). It takes two arguments and returns a float. It is uncommon to use math.pow().

**Task**<br>
You are given three integers: **a**, **b**, and **m**. Print two lines.<br>
On the first line, print the result of pow(a,b). On the second line, print the result of pow(a,b,m).

**Input Format**<br>
The first line contains **a**, the second line contains **b**, and the third line contains **m**.

**Constraints**<br>
* **1 <= a <= 10**
* **1 <= b <= 10**
* **2 <= m <= 1000**

**Sample Input**<br>
`3`<br>
`4`<br>
`5`

**Sample Output**<br>
`81`<br>
`1`

In [11]:
a = int(input())
b = int(input())
m = int(input())
print(pow(a, b))
print(pow(a, b, m))

3
4
5
81
1


# 21. [Find a string](https://www.hackerrank.com/challenges/find-a-string/problem?h_r=profile&isFullScreen=true)

In this challenge, the user enters a string and a substring. You have to print the number of times that the substring occurs in the given string. String traversal will take place from left to right, not from right to left.

**NOTE:** String letters are case-sensitive.

**Input Format**<br>
The first line of input contains the original string. The next line contains the substring.

**Constraints**
* **1 ≤ len(string) ≤ 200**<br>
Each character in the string is an ascii character.

**Output Format**

Output the integer number indicating the total number of occurrences of the substring in the original string.

**Sample Input**<br>
`ABCDCDC`<br>
`CDC`

**Sample Output**<br>
`2`

**Concept**<br>
Some string processing examples, [such as these](http://www.thelearningpoint.net/computer-science/learning-python-programming-and-data-structures/learning-python-programming-and-data-structures--tutorial-12--string-manipulation), might be useful.<br>
There are a couple of new concepts:<br>
In Python, the length of a string is found by the function len(s), where  is the string.<br>
To traverse through the length of a string, use a for loop:<br>
<p><b>for i in range(0, len(s)):</b><br>
&emsp;<b>print (s[i])</b></p>
    
A range function is used to loop over some length:<br>
`range (0, 5)`

Here, the range loops over **0** to **4**. **5** is excluded.

In [1]:
def count_substring(string, sub_string):
    position = 0
    count = 0
    
    while string.find(sub_string, position) != -1:
        count += 1
        position = string.find(sub_string, position) + 1
    
    return count

string = input().strip()
sub_string = input().strip()

count = count_substring(string, sub_string)
print(count)

ABCDCDC
CDC
2


# 22. [Text Alignment](https://www.hackerrank.com/challenges/text-alignment/problem?h_r=profile&isFullScreen=true)

In Python, a string of text can be aligned left, right and center.

**.ljust(width)**<br>
This method returns a left aligned string of length width.

`>>> width = 20`<br>
`>>> print 'HackerRank'.ljust(width,'-')`<br>
`HackerRank----------`

**.center(width)**<br>
This method returns a centered string of length width.

`>>> width = 20`<br>
`>>> print 'HackerRank'.center(width,'-')`<br>
`-----HackerRank-----`

**.rjust(width)**<br>
This method returns a right aligned string of length width.

`>>> width = 20`<br>
`>>> print 'HackerRank'.rjust(width,'-')`<br>
`----------HackerRank`

**Task**<br>
You are given a partial code that is used for generating the HackerRank Logo of variable thickness.<br>
Your task is to replace the blank `(______)` with rjust, ljust or center.

**Input Format**<br>
A single line containing the thickness value for the logo.

**Constraints**<br>
The thickness must be an odd number.<br>
**0 < thickness < 50**

**Output Format**<br>
Output the desired logo.

**Sample Input**<br>
`5`

**Sample Output**

        H
       HHH   
      HHHHH  
     HHHHHHH 
    HHHHHHHHH
      HHHHH               HHHHH             
      HHHHH               HHHHH             
      HHHHH               HHHHH             
      HHHHH               HHHHH             
      HHHHH               HHHHH             
      HHHHH               HHHHH             
      HHHHHHHHHHHHHHHHHHHHHHHHH   
      HHHHHHHHHHHHHHHHHHHHHHHHH   
      HHHHHHHHHHHHHHHHHHHHHHHHH   
      HHHHH               HHHHH             
      HHHHH               HHHHH             
      HHHHH               HHHHH             
      HHHHH               HHHHH             
      HHHHH               HHHHH             
      HHHHH               HHHHH             
                        HHHHHHHHH 
                         HHHHHHH  
                          HHHHH   
                           HHH    
                            H `

In [2]:
thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))


5
    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


# 23. [Text Wrap](https://www.hackerrank.com/challenges/text-wrap/problem?h_r=profile&isFullScreen=true)

You are given a string **S** and width **w**.<br>
Your task is to wrap the string into a paragraph of width **w**.

**Function Description**<br>
Complete the wrap function in the editor below.<br>
wrap has the following parameters:
* string string: a long string
* int max_width: the width to wrap to

**Returns**
* string: a single string with newline characters ('\n') where the breaks should be

**Input Format**<br>
The first line contains a string, **string**.<br>
The second line contains the width, **maxwidth**.

**Constraints**
* **0 < len(string) < 1000**
* **0 < maxwidth < len(string)**

**Sample Input 0**<br>
ABCDEFGHIJKLIMNOQRSTUVWXYZ<br>
4

**Sample Output 0**<br>
ABCD<br>
EFGH<br>
IJKL<br>
IMNO<br>
QRST<br>
UVWX<br>
YZ

In [3]:
import textwrap

def wrap(string, max_width):
    return textwrap.fill(string, max_width)

string, max_width = input(), int(input())
result = wrap(string, max_width)
print(result)

ABCDEFGHIJKLIMNOQRSTUVWXYZ
4
ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ


# 24. [Designer Door Mat](https://www.hackerrank.com/challenges/designer-door-mat/problem?h_r=profile&isFullScreen=true)

Mr. Vincent works in a door mat manufacturing company. One day, he designed a new door mat with the following specifications:
* Mat size must be **M X N**. (**N** is an odd natural number, and **M** is **3** times **N**.)
* The design should have 'WELCOME' written in the center.
* The design pattern should only use |, . and - characters.

**Sample Designs**

    Size: 7 x 21 
    ---------.|.---------
    ------.|..|..|.------
    ---.|..|..|..|..|.---
    -------WELCOME-------
    ---.|..|..|..|..|.---
    ------.|..|..|.------
    ---------.|.---------
    
    Size: 11 x 33
    ---------------.|.---------------
    ------------.|..|..|.------------
    ---------.|..|..|..|..|.---------
    ------.|..|..|..|..|..|..|.------
    ---.|..|..|..|..|..|..|..|..|.---
    -------------WELCOME-------------
    ---.|..|..|..|..|..|..|..|..|.---
    ------.|..|..|..|..|..|..|.------
    ---------.|..|..|..|..|.---------
    ------------.|..|..|.------------
    ---------------.|.---------------
    
**Input Format**<br>
A single line containing the space separated values of **N** and **M**.

**Constraints**
* **5 < N < 101**
* **15 < M < 303**

**Output Format**<br>
Output the design pattern.

**Sample Input**<br>
`9 27`

**Sample Output**

    ------------.|.------------
    ---------.|..|..|.---------
    ------.|..|..|..|..|.------
    ---.|..|..|..|..|..|..|.---
    ----------WELCOME----------
    ---.|..|..|..|..|..|..|.---
    ------.|..|..|..|..|.------
    ---------.|..|..|.---------
    ------------.|.------------

In [4]:
n, m=map(int, input().split())

# top
for i in range(1,n,2):
    print((".|."*i).center(m,"-"))

# CENTER
print("WELCOME".center(m,"-"))

# Bottom
for i in range(n-2,0,-2):
    print((".|."*i).center(m,"-"))


9 27
------------.|.------------
---------.|..|..|.---------
------.|..|..|..|..|.------
---.|..|..|..|..|..|..|.---
----------WELCOME----------
---.|..|..|..|..|..|..|.---
------.|..|..|..|..|.------
---------.|..|..|.---------
------------.|.------------


# 25. [String Formatting](https://www.hackerrank.com/challenges/python-string-formatting/problem?h_r=profile&isFullScreen=true)

Given an integer, **n**, print the following values for each integer **i** from **1** to **n**:
1. Decimal
2. Octal
3. Hexadecimal (capitalized)
4. Binary

**Function Description**

Complete the print_formatted function in the editor below.<br>
print_formatted has the following parameters:
* int number: the maximum value to print

**Prints**

The four values must be printed on a single line in the order specified above for each **i** from **1** to **number**. Each value should be space-padded to match the width of the binary value of **number** and the values should be separated by a single space.

**Input Format**

A single integer denoting **n**.

**Constraints**
* **1 ≤ n ≤ 99**

**Sample Input**<br>
`17`

**Sample Output**

        1     1     1     1
        2     2     2    10
        3     3     3    11
        4     4     4   100
        5     5     5   101
        6     6     6   110
        7     7     7   111
        8    10     8  1000
        9    11     9  1001
       10    12     A  1010
       11    13     B  1011
       12    14     C  1100
       13    15     D  1101
       14    16     E  1110
       15    17     F  1111
       16    20    10 10000
       17    21    11 10001

In [1]:
def print_formatted(number):
    # your code goes here
    width = len(bin(number)[2:]) + 1
    for i in range(1, number + 1):
        octal = oct(i)[2:]
        hexa = hex(i)[2:].upper()
        binary = bin(i)[2:]
        out = (str(i)).rjust(width)+(octal).rjust(width)+(hexa).rjust(width)+(binary).rjust(width)
        print(out[1:])
        
n = int(input())
print_formatted(n)

17
    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001


# 26. [Mod Divmod](https://www.hackerrank.com/challenges/python-mod-divmod/problem?h_r=profile&isFullScreen=true)

One of the built-in functions of Python is divmod, which takes two arguments **a** and **b** and returns a tuple containing the quotient of **a/b** first and then the remainder **a**.

For example:

>`>>> print divmod(177,10)`<br>
`(17, 7)`

Here, the integer division is `177/10 => 17` and the modulo operator is `177%10 => 7`.

**Task**

Read in two integers, **a** and **b**, and print three lines.<br>
The first line is the integer division **a//b** (While using Python2 remember to import `division` from `__future__`).<br>
The second line is the result of the modulo operator: **a%b**.<br>
The third line prints the divmod of **a** and **b**.

**Input Format**

The first line contains the first integer, **a**, and the second line contains the second integer, **b**.

**Output Format**

Print the result as described above.

**Sample Input**<br>
`177`<br>
`10`

**Sample Output**<br>
`17`<br>
`7`<br>
`(17, 7)`

In [2]:
a = int(input())
b = int(input())

print(divmod(a, b)[0])
print(divmod(a, b)[1])
print(divmod(a, b))

177
10
17
7
(17, 7)


# 27. [Integers Come In All Sizes](https://www.hackerrank.com/challenges/python-integers-come-in-all-sizes/problem?h_r=profile&isFullScreen=true)

Integers in Python can be as big as the bytes in your machine's memory. There is no limit in size as there is: **2<sup>31</sup> - 1** (c++ int) or **2<sup>63</sup> - 1** (C++ long long int).

As we know, the result of **a<sup>b</sup>** grows really fast with increasing **b**.

Let's do some calculations on very large integers.

**Task**<br>
Read four numbers, **a**, **b**, **c**, and **d**, and print the result of **a<sup>b</sup> + c<sup>d</sup>**.

**Input Format**<br>
Integers **a**, **b**, **c**, and **d** are given on four separate lines, respectively.

**Constraints**
* **1 ≤ a ≤ 1000**
* **1 ≤ b ≤ 1000**
* **1 ≤ c ≤ 1000**
* **1 ≤ d ≤ 1000**

**Output Format**<br>
Print the result of **a<sup>b</sup> + c<sup>d</sup>** on one line.

**Sample Input**<br>
`9`<br>
`29`<br>
`7`<br>
`27`<br>

**Sample Output**<br>
4710194409608608369201743232

**Note:** This result is bigger than **2<sup>63</sup> - 1**. Hence, it won't fit in the long long int of C++ or a 64-bit integer.

In [3]:
a = int(input())
b = int(input())
c = int(input())
d = int(input())

print((a ** b) + (c ** d))

9
29
7
27
4710194409608608369201743232


# 28. [itertools.product()](https://www.hackerrank.com/challenges/itertools-product/problem?h_r=profile&isFullScreen=true)

This tool computes the [cartesian product](https://en.wikipedia.org/wiki/Cartesian_product) of input iterables.<br>
It is equivalent to nested for-loops.<br>
For example, `product(A, B)` returns the same as `((x,y) for x in A for y in B)`.

**Sample Code**<br>
> `>>> from itertools import product`<br>
> `>>>`<br>
> `>>> print list(product([1,2,3],repeat = 2))`<br>
> `[(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3)]`<br>
`>>>`<br>
`>>> print list(product([1,2,3],[3,4]))`<br>
`[(1, 3), (1, 4), (2, 3), (2, 4), (3, 3), (3, 4)]`<br>
`>>>`<br>
`>>> A = [[1,2,3],[3,4,5]]`<br>
`>>> print list(product(*A))`<br>
`[(1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 3), (3, 4), (3, 5)]`<br>
`>>>`<br>
`>>> B = [[1,2,3],[3,4,5],[7,8]]`<br>
`>>> print list(product(*B))`<br>
`[(1, 3, 7), (1, 3, 8), (1, 4, 7), (1, 4, 8), (1, 5, 7), (1, 5, 8), (2, 3, 7), (2, 3, 8), (2, 4, 7), (2, 4, 8), (2, 5, 7), (2, 5, 8), (3, 3, 7), (3, 3, 8), (3, 4, 7), (3, 4, 8), (3, 5, 7), (3, 5, 8)]`

**Task**

You are given a two lists **A** and **B**. Your task is to compute their cartesian product **A**[X](https://en.wikipedia.org/wiki/Cartesian_product)**B**.

**Example**
> `A = [1, 2]`<br>
`B = [3, 4]`
> 
> `AxB = [(1, 3), (1, 4), (2, 3), (2, 4)]`

**Note:** **A** and **B** are sorted lists, and the cartesian product's tuples should be output in sorted order.

**Input Format**

The first line contains the space separated elements of list **A**.<br>
The second line contains the space separated elements of list **B**.

Both lists have no duplicate integer elements.

**Constraints**
* **0 < A < 30**
* **0 < B < 30**

**Output Format**

Output the space separated tuples of the cartesian product.

**Sample Input**
> `1 2`<br>
> `3 4`

**Sample Output**
> `(1, 3) (1, 4) (2, 3) (2, 4)`

In [1]:
from itertools import product

a, b = map(int, input().split()), map(int, input().split())
axb = list(product(a, b))
print(*axb)

1 2
3 4
(1, 3) (1, 4) (2, 3) (2, 4)


# 29. [Arrays](https://www.hackerrank.com/challenges/np-arrays/problem?h_r=profile&isFullScreen=true)

The NumPy (Numeric Python) package helps us manipulate large arrays and matrices of numeric data.

To use the NumPy module, we need to import it using:

> `import numpy`

**Arrays**

A NumPy array is a grid of values. They are similar to lists, except that every element of an array must be the same type.

> `import numpy`
> 
> `a = numpy.array([1,2,3,4,5])`<br>
> `print a[1]          #2`
>
> `b = numpy.array([1,2,3,4,5],float)`<br>
> `print b[1]          #2.0`

In the above example, numpy.array() is used to convert a list into a NumPy array. The second argument (float) can be used to set the type of array elements.

**Task**

You are given a space separated list of numbers.<br>
Your task is to print a reversed NumPy array with the element type float.

**Input Format**

A single line of input containing space separated numbers.

**Output Format**

Print the reverse NumPy array with type float.

**Sample Input**
> `1 2 3 4 -8 -10`

**Sample Output**
> `[-10.  -8.   4.   3.   2.   1.]`

In [3]:
import numpy

def arrays(arr):
    arr = numpy.array(arr, float)
    arr = numpy.flip(arr)
    return arr

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# 30. [Introduction to Sets](https://www.hackerrank.com/challenges/py-introduction-to-sets/problem?h_r=profile&isFullScreen=true)

A set is an unordered collection of elements without duplicate entries.<br>
When printed, iterated or converted into a sequence, its elements will appear in an arbitrary order.

**Example**

> `>>> print set()`<br>
> `set([])`

> `>>> print set('HackerRank')`<br>
> `set(['a', 'c', 'e', 'H', 'k', 'n', 'r', 'R'])`<br>

> `>>> print set([1,2,1,2,3,4,5,6,0,9,12,22,3])`<br>
> `set([0, 1, 2, 3, 4, 5, 6, 9, 12, 22])`<br>

> `>>> print set((1,2,3,4,5,5))`<br>
> `set([1, 2, 3, 4, 5])`<br>

> `>>> print set(set(['H','a','c','k','e','r','r','a','n','k']))`<br>
> `set(['a', 'c', 'r', 'e', 'H', 'k', 'n'])`<br>

> `>>> print set({'Hacker' : 'DOSHI', 'Rank' : 616 })`<br>
> `set(['Hacker', 'Rank'])`<br>

> `>>> print set(enumerate(['H','a','c','k','e','r','r','a','n','k']))`<br>
> `set([(6, 'r'), (7, 'a'), (3, 'k'), (4, 'e'), (5, 'r'), (9, 'k'), (2, 'c'), (0, 'H'), (1, 'a'), (8, 'n')])`<br>

Basically, sets are used for membership testing and eliminating duplicate entries.

**Task**

Now, let's use our knowledge of sets and help Mickey.

Ms. Gabriel Williams is a botany professor at District College. One day, she asked her student Mickey to compute the average of all the plants with distinct heights in her greenhouse.

Formula used:
> ***Average = Sum of Distinct Heights / Total Number of Distinct Heights***

**Function Description**

Complete the average function in the editor below.<br>
average has the following parameters:
* int arr: an array of integers

**Returns**
* float: the resulting float value rounded to 3 places after the decimal

**Input Format**<br>
The first line contains the integer, **N**, the size of **arr**.
The second line contains the **N** space-separated integers, **arr[i]**.

**Constraints**
* **0 < N ≤ 100**

**Sample Input**

    STDIN                                       Function
    -----                                       --------
    10                                          arr[] size N = 10
    161 182 161 154 176 170 167 171 170 174     arr = [161, 181, ..., 174]

**Sample Output**<br>
`169.375`

**Explanation**

Here, **set([154,161,167,170,171,174,176,182])** is the set containing the distinct heights. Using the sum() and len() functions, we can compute the average.
> **Average = 1355/8 = 169.375**

In [1]:
def average(array):
    # your code goes here
    array = set(array)
    res = sum(array)/len(array)
    return res

n = int(input())
arr = list(map(int, input().split()))
result = average(arr)
print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


# 31. [Set .add()](https://www.hackerrank.com/challenges/py-set-add/problem?h_r=profile&isFullScreen=true)

If we want to add a single element to an existing set, we can use the .add() operation.<br>
It adds the element to the set and returns 'None'.

**Example**
> `>>> s = set('HackerRank')`<br>
`>>> s.add('H')`<br>
`>>> print s`<br>
`set(['a', 'c', 'e', 'H', 'k', 'n', 'r', 'R'])`<br>
`>>> print s.add('HackerRank')`<br>
`None`<br>
`>>> print s`<br>
`set(['a', 'c', 'e', 'HackerRank', 'H', 'k', 'n', 'r', 'R'])`<br>

**Task**

Apply your knowledge of the .add() operation to help your friend Rupal.

Rupal has a huge collection of country stamps. She decided to count the total number of distinct country stamps in her collection. She asked for your help. You pick the stamps one by one from a stack of **N** country stamps.

Find the total number of distinct country stamps.

**Input Format**

The first line contains an integer **N**, the total number of country stamps.
The next **N** lines contains the name of the country where the stamp is from.

**Constraints**
* **0 < N < 1000**

**Output Format**

Output the total number of distinct country stamps on a single line.

**Sample Input**

`7`<br>
`UK`<br>
`China`<br>
`USA`<br>
`France`<br>
`New Zealand`<br>
`UK`<br>
`France`<br>

**Sample Output**<br>
`5`

**Explanation**

UK and France repeat twice. Hence, the total number of distinct country stamps is **5** (five).

In [2]:
n = int(input())
s = set()

for i in range(n):
    s.add(input())

print(len(s))

7
UK
China
USA
France
New Zealand
UK
France
5


# 32. [Shape and Reshape](https://www.hackerrank.com/challenges/np-shape-reshape/problem?h_r=profile&isFullScreen=true)

**[shape](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy-ndarray-shape)**

The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.

**(a). Using shape to get array dimensions**
> `import numpy`
>
> `my__1D_array = numpy.array([1, 2, 3, 4, 5])`<br>
`print my_1D_array.shape     #(5,) -> 1 row and 5 columns`
>
> `my__2D_array = numpy.array([[1, 2],[3, 4],[6,5]])`<br>
`print my_2D_array.shape     #(3, 2) -> 3 rows and 2 columns` 

**(b). Using shape to change array dimensions**

> `import numpy`
> 
> `change_array = numpy.array([1,2,3,4,5,6])`<br>
`change_array.shape = (3, 2)`<br>
`print change_array`
>
> `#Output`<br>
`[[1 2]`<br>
`[3 4]`<br>
`[5 6]]`

**[reshape](http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape)**

The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.

> `import numpy`
> 
> `my_array = numpy.array([1,2,3,4,5,6])`<br>
`print numpy.reshape(my_array,(3,2))`<br>
> 
> `#Output`<br>
`[[1 2]`<br>
`[3 4]`<br>
`[5 6]]`<br>

**Task**

You are given a space separated list of nine integers. Your task is to convert this list into a **3X3** NumPy array.

**Input Format**<br>
A single line of input containing **9** space separated integers.

**Output Format**<br>
Print the **3X3** NumPy array.

**Sample Input**<br>
`1 2 3 4 5 6 7 8 9`

**Sample Output**<br>
`[[1 2 3]`<br>
 `[4 5 6]`<br>
 `[7 8 9]]`<br>

In [3]:
import numpy

arr = list(map(int, input().split()))
print(numpy.reshape(arr, (3, 3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 33. [Zeros and Ones](https://www.hackerrank.com/challenges/np-zeros-and-ones/problem?h_r=profile&isFullScreen=true)

[zeros](http://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy-zeros)<br>
The zeros tool returns a new array with a given shape and type filled with **0**'s.

> `import numpy`
>
> `print numpy.zeros((1,2))                    #Default type is float`<br>
`#Output : [[ 0.  0.]]`
>
> `print numpy.zeros((1,2), dtype = numpy.int) #Type changes to int`<br>
`#Output : [[0 0]]`

[ones](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy-ones)<br>
The ones tool returns a new array with a given shape and type filled with **1**'s.

> `import numpy`
>
> `print numpy.ones((1,2))                    #Default type is float`<br>
`#Output : [[ 1.  1.]]`
>
> `print numpy.ones((1,2), dtype = numpy.int) #Type changes to int`<br>
`#Output : [[1 1]]`

**Task**<br>
You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools `numpy.zeros` and `numpy.ones`.

**Input Format**<br>
A single line containing the space-separated integers.

**Constraints**
* **1 ≤ each integer ≤ 3**

**Output Format**<br>
First, print the array using the `numpy.zeros` tool and then print the array with the `numpy.ones` tool.

**Sample Input 0**

3 3 3

**Sample Output 0**

[[[0 0 0]<br>
  [0 0 0]<br>
  [0 0 0]]

 [[0 0 0]<br>
  [0 0 0]<br>
  [0 0 0]]

 [[0 0 0]<br>
  [0 0 0]<br>
  [0 0 0]]]<br>
[[[1 1 1]<br>
  [1 1 1]<br>
  [1 1 1]]

 [[1 1 1]<br>
  [1 1 1]<br>
  [1 1 1]]

 [[1 1 1]<br>
  [1 1 1]<br>
  [1 1 1]]]
  
**Explanation 0**

Print the array built using `numpy.zeros` and `numpy.ones` tools and you get the result as shown.

In [1]:
import numpy as np

n = tuple(map(int, input().split()))
print(np.zeros(n, dtype = np.int_))
print(np.ones(n, dtype = np.int_))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# 34. [Transpose and Flatten](https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem?h_r=profile&isFullScreen=true)

[Transpose](http://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html#numpy-transpose)<br>
We can generate the transposition of an array using the tool `numpy.transpose`.
It will not affect the original array, but it will create a new array.

> `import numpy`
>
> `my_array = numpy.array([[1,2,3],`<br>
> `                   [4,5,6]])`<br>
> `print numpy.transpose(my_array)`<br>
>
>`#Output`<br>
`[[1 4]`<br>
` [2 5]`<br>
` [3 6]]`

[Flatten](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html)<br>
The tool flatten creates a copy of the input array flattened to one dimension.

> `import numpy`
>
> `my_array = numpy.array([[1,2,3],`<br>
> `                   [4,5,6]])`<br>
> `print my_array.flatten()`<br>
>
> `#Output`<br>
`[1 2 3 4 5 6]`

**Task**<br>
You are given a **N**X**M** integer array matrix with space separated elements (**N** = rows and **M** = columns).<br>
Your task is to print the transpose and flatten results.

**Input Format**<br>
The first line contains the space separated values of **N** and **M**.
The next **N** lines contains the space separated elements of **M** columns.

**Output Format**<br>
First, print the transpose array and then print the flatten.

**Sample Input**

`2 2`<br>
`1 2`<br>
`3 4`

**Sample Output**

`[[1 3]`<br>
` [2 4]]`<br>
`[1 2 3 4]`

In [1]:
import numpy as np

n, m = map(int, input().split())
data = np.array([input().split() for _ in range(n)], int)

print(np.transpose(data))
print(data.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]
